version: "3.9"  # optional since v1.27.0
services:
  web:
     build: php56
     environment:
       - ALLOW_OVERRIDE=true
     ports:
       - "9080:80"
       - "9443:443"
     links:
       - db
     volumes:
       - ./html:/var/www/html/

  db:
    build: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
      - "8889:3306"

